### ISSUE TITLE
plugin was not found in the index? using lobechat search engine plugin on m1 macbook pro 16 inch running mac os sonoma latest version.

### ISSUE THREAD

**Issue by Lokii55** [lobehub/lobe-chat-plugins#26]
{
  "identifier": "engine",
  "message": "[gateway] plugin 'engine' is not found，please check the plugin list in https://chat-plugins.lobehub.com, or create an issue to [lobe-chat-plugins](https://github.com/lobehub/lobe-chat-plugins/issues)"
}

**Comment by arvinxx** [comment]
I think it's the ability of model's function calling return the wrong identifier

**Comment by Lokii55** [comment]
how do i fix it?

**Comment by Lokii55** [comment]
> I think it's the ability of model's function calling return the wrong identifier

that doesnt help me, can you explain what you mean?

**Comment by arvinxx** [comment]
@Lokii55 you can take a screenshot of your error. I think it's an issue of the model you are using, if you switch to openai's gpt-3.5 or gpt-4, this error won't show.
